.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. i0coin_qt test_bitcoin_qt
clean: FORCE
	$(MAKE) -C .. i0coin_qt_clean test_bitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoin_qt_check
i0coin-qt i0coin-qt.exe: FORCE
	 $(MAKE) -C .. i0coin_qt
